### ISSUE TITLE
[Bug]: Error with ONNX inference

### ISSUE THREAD

**Issue by glucasol** [openvinotoolkit/anomalib#1085]
### Describe the bug

I have created an ONNX model and  optmized it using [Intel Neural Compressor](https://github.com/intel/neural-compressor) with the following code:
````
# Built-in dummy dataset
dataset = Datasets('onnxrt_qlinearops')['dummy'](shape=[(1, 3, 256, 256)], label=True)
# Built-in calibration dataloader and evaluation dataloader for Quantization.
dataloader = DataLoader(framework='onnxrt_qlinearops', dataset=dataset)
# Post Training Quantization Config
config = PostTrainingQuantConfig()
# Please modify the eval_func if you using the real dataset
def eval_func(model):
    return 1
# Just call fit to do quantization.
q_model = fit(model="./model.onnx",
              conf=config,
              calib_dataloader=dataloader,
              eval_dataloader=dataloader,
              eval_func = eval_func
              )
q_model.save("./q_model.onnx")
````

Now I want to run openvino inference specifying this optimized ONNX model and it gives me the following error:
````
Traceback (most recent call last):
  File "tools/inference/openvino_inference.py", line 101, in <module>
    infer()
  File "tools/inference/openvino_inference.py", line 75, in infer
    inferencer = OpenVINOInferencer(config=args.config, path=args.weights, meta_data_path=args.meta_data)
  File "/home/gabrieloliveira/Documents/anomalib/anomalib/deploy/inferencers/openvino_inferencer.py", line 49, in __init__
    self.input_blob, self.output_blob, self.network = self.load_model(path)
  File "/home/gabrieloliveira/Documents/anomalib/anomalib/deploy/inferencers/openvino_inferencer.py", line 77, in load_model
    network = ie_core.read_network(path)
  File "ie_api.pyx", line 367, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 410, in openvino.inference_engine.ie_api.IECore.read_network
RuntimeError: Check 'unknown_operators.empty()' failed at src/frontends/onnx/frontend/src/core/graph.cpp:213:
OpenVINO does not support the following ONNX operations: com.microsoft.QLinearAdd, com.microsoft.QLinearConcat, com.microsoft.QLinearMul
````

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

Train the standard Padim anomally detection model and export it to ONNX.
Quantize it using [Intel Neural Compressor](https://github.com/intel/neural-compressor) with the following code:
````
# Built-in dummy dataset
dataset = Datasets('onnxrt_qlinearops')['dummy'](shape=[(1, 3, 256, 256)], label=True)
# Built-in calibration dataloader and evaluation dataloader for Quantization.
dataloader = DataLoader(framework='onnxrt_qlinearops', dataset=dataset)
# Post Training Quantization Config
config = PostTrainingQuantConfig()
# Please modify the eval_func if you using the real dataset
def eval_func(model):
    return 1
# Just call fit to do quantization.
q_model = fit(model="./model.onnx",
              conf=config,
              calib_dataloader=dataloader,
              eval_dataloader=dataloader,
              eval_func = eval_func
              )
q_model.save("./q_model.onnx")
````
Finally, run openvino inference.

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.8.10]
- Anomalib version: [e.g. 0.3.7]
- PyTorch version: [e.g. 1.12.0]
- CPU

### Expected behavior

I expect the command to run openvino inference successfully.

### Pip/GitHub

pip

### Configuration YAML

```yaml
dataset:
  name: mvtec #options: [mvtec, btech, folder]
  format: mvtec
  path: ./datasets/MVTec
  category: bottle
  task: segmentation
  image_size: 256
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 8
  transform_config:
    train: null
    val: null
  create_validation_set: false
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: padim
  backbone: resnet18
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: openvino #options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  accumulate_grad_batches: 1
  amp_backend: native
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gpus: null # Set automatically
  gradient_clip_val: 0
  ipus: null
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  max_epochs: 1
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  sync_batchnorm: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0 # Don't validate before extracting features.
```

### Logs

```shell
Traceback (most recent call last):
  File "tools/inference/openvino_inference.py", line 101, in <module>
    infer()
  File "tools/inference/openvino_inference.py", line 75, in infer
    inferencer = OpenVINOInferencer(config=args.config, path=args.weights, meta_data_path=args.meta_data)
  File "/home/gabrieloliveira/Documents/anomalib/anomalib/deploy/inferencers/openvino_inferencer.py", line 49, in __init__
    self.input_blob, self.output_blob, self.network = self.load_model(path)
  File "/home/gabrieloliveira/Documents/anomalib/anomalib/deploy/inferencers/openvino_inferencer.py", line 77, in load_model
    network = ie_core.read_network(path)
  File "ie_api.pyx", line 367, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 410, in openvino.inference_engine.ie_api.IECore.read_network
RuntimeError: Check 'unknown_operators.empty()' failed at src/frontends/onnx/frontend/src/core/graph.cpp:213:
OpenVINO does not support the following ONNX operations: com.microsoft.QLinearAdd, com.microsoft.QLinearConcat, com.microsoft.QLinearMul
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blaz-r** [comment]
Hello @glucasol . As seen on Intel Neural Compressor page, it is not intended to work with OpenVINO. OpenVINO ONNX frontend doesn't currently support these operations according to https://github.com/openvinotoolkit/openvino/issues/16660. You'll need to use other optimization tools, like [OpenVINO nncf](https://github.com/openvinotoolkit/nncf)
Hope this helps.

**Comment by Kyle-fang** [comment]
Hello! I'm using onnx obtained from anomalib and then reasoning with onnxruntime, the input image shape is [1, 3, 256, 256] but the output is [1, 1, 256, 256], isn't it supposed to be the number of categories? Is there a problem with the .onnx file? @blaz-r @

**Comment by Kyle-fang** [comment]
Thank you very much for your reply and answer. I understand the meaning of the output. But how can such output determine whether the sample is abnormal? I hope to obtain the output of whether the input sample is an abnormal sample when reasoning.

---Original---
From: "Blaž ***@***.***&gt;
Date: Thu, Jul 20, 2023 20:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [openvinotoolkit/anomalib] [Bug]: Error with ONNX inference(Issue #1085)




 
Hello. The output of anomaly detection is usually an anomaly map, whose width and height is the same as the input image. It does have only one channel, unlike the input that has 3 (R, G and B) because anomaly map is per pixel score of how anomalous that pixel/region is, therefore just one number -&gt; 1 channel.
