### ISSUE TITLE
[Bug]: AttributeError: 'AnomalibMetricCollection' object has no attribute 'image_F1Score'

### ISSUE THREAD

**Issue by kumarsyamala** [openvinotoolkit/anomalib#1115]
### Describe the bug

I am trying to train the model with leather dataset 

Then I am facing this error

Any suggestions how I can tackle this problem, I have searched and couldnt get the solution. 

` AttributeError: 'AnomalibMetricCollection' object has no attribute 'image_F1Score'`

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

!git clone https://github.com/openvinotoolkit/anomalib.git
%cd anomalib
!pip install -e .
!python tools/train.py --config C:\anomalib.yaml

### OS information

OS information:
- OS: [e.g. Windows 11]
- Python version: [e.g. 3.8.16]
- PyTorch version: [e.g. 1.9.0]

### Expected behavior

It should have run and get the results; I already trained the model with bottle and got the result when I am trying with different category like leather and wood giving the same error.

### Pip/GitHub

pip

### Configuration YAML

```yaml
dataset:
  name: mvtec
  format: mvtec
  path: C:\Users\Rama.Reddy\Downloads\defect\defect_anamoly
  category: leather
  task: segmentation
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: padim
  backbone: resnet18
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null # options: torch, onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

### Logs

```shell
C:\Users\Rama.Reddy\Downloads\defect\anomalib\src\anomalib\config\config.py:275: UserWarning: config.project.unique_dir is set to False. This does not ensure that your results will be written in an empty directory and you may overwrite files.
  warn(
Global seed set to 42
2023-06-07 17:35:39,883 - anomalib.data - INFO - Loading the datamodule
2023-06-07 17:35:39,885 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2023-06-07 17:35:39,887 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2023-06-07 17:35:39,887 - anomalib.models - INFO - Loading the model.
2023-06-07 17:35:39,889 - anomalib.models.components.base.anomaly_module - INFO - Initializing PadimLightning model.
c:\Users\Rama.Reddy\Anaconda3\envs\hand\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
2023-06-07 17:35:39,916 - anomalib.models.components.feature_extractors.timm - WARNING - FeatureExtractor is deprecated. Use TimmFeatureExtractor instead. Both FeatureExtractor and TimmFeatureExtractor will be removed in a future release.
2023-06-07 17:35:41,067 - timm.models.helpers - INFO - Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
2023-06-07 17:35:42,014 - anomalib.utils.loggers - INFO - Loading the experiment logger(s)
2023-06-07 17:35:42,014 - anomalib.utils.callbacks - INFO - Loading the callbacks
C:\Users\Rama.Reddy\Downloads\defect\anomalib\src\anomalib\utils\callbacks\__init__.py:142: UserWarning: Export option: None not found. Defaulting to no model export
  warnings.warn(f"Export option: {config.optimization.export_mode} not found. Defaulting to no model export")
2023-06-07 17:35:42,364 - pytorch_lightning.utilities.rank_zero - INFO - GPU available: False, used: False
2023-06-07 17:35:42,365 - pytorch_lightning.utilities.rank_zero - INFO - TPU available: False, using: 0 TPU cores
2023-06-07 17:35:42,365 - pytorch_lightning.utilities.rank_zero - INFO - IPU available: False, using: 0 IPUs
2023-06-07 17:35:42,365 - pytorch_lightning.utilities.rank_zero - INFO - HPU available: False, using: 0 HPUs
2023-06-07 17:35:42,365 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
2023-06-07 17:35:42,366 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
2023-06-07 17:35:42,366 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_test_batches=1.0)` was configured so 100% of the batches will be used..
2023-06-07 17:35:42,366 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_predict_batches=1.0)` was configured so 100% of the batches will be used..
2023-06-07 17:35:42,366 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
2023-06-07 17:35:42,366 - anomalib - INFO - Training the model.
2023-06-07 17:35:42,415 - anomalib.data.mvtec - INFO - Found the dataset.
c:\Users\Rama.Reddy\Anaconda3\envs\hand\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: Metric `ROC` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\core\optimizer.py:183: UserWarning: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer
  rank_zero_warn(
2023-06-07 17:35:42,902 - pytorch_lightning.callbacks.model_summary - INFO - 
  | Name                  | Type                     | Params
-------------------------------------------------------------------
0 | image_threshold       | AnomalyScoreThreshold    | 0     
1 | pixel_threshold       | AnomalyScoreThreshold    | 0     
2 | model                 | PadimModel               | 2.8 M 
3 | image_metrics         | AnomalibMetricCollection | 0     
4 | pixel_metrics         | AnomalibMetricCollection | 0     
5 | normalization_metrics | MinMax                   | 0     
-------------------------------------------------------------------
2.8 M     Trainable params
0         Non-trainable params
2.8 M     Total params
11.131    Total estimated model params size (MB)
C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py:138: UserWarning: `training_step` returned `None`. If this was on purpose, ignore this warning...
  self.warning_cache.warn("`training_step` returned `None`. If this was on purpose, ignore this warning...")
2023-06-07 17:41:34,260 - anomalib.models.padim.lightning_model - INFO - Aggregating the embedding extracted from the training set.
2023-06-07 17:41:34,424 - anomalib.models.padim.lightning_model - INFO - Fitting a Gaussian to the embedding collected from the training set.
Traceback (most recent call last):
  File "tools/train.py", line 81, in <module>
    train(args)
  File "tools/train.py", line 66, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\trainer\trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\trainer\trainer.py", line 1112, in _run
    results = self._run_stage()
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\trainer\trainer.py", line 1191, in _run_stage
    self._run_train()
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\trainer\trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\loops\fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\loops\loop.py", line 200, in run
    self.on_advance_end()
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 250, in on_advance_end
    self._run_validation()
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 308, in _run_validation
    self.val_loop.run()
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\loops\loop.py", line 206, in run
    output = self.on_run_end()
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 180, in on_run_end
    self._evaluation_epoch_end(self._outputs)
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 288, in _evaluation_epoch_end
    self.trainer._call_lightning_module_hook(hook_name, output_or_outputs)
  File "C:\Users\Rama.Reddy\AppData\Roaming\Python\Python38\site-packages\pytorch_lightning\trainer\trainer.py", line 1356, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "C:\Users\Rama.Reddy\Downloads\defect\anomalib\src\anomalib\models\components\base\anomaly_module.py", line 146, in validation_epoch_end
    self._collect_outputs(self.image_metrics, self.pixel_metrics, outputs)
  File "C:\Users\Rama.Reddy\Downloads\defect\anomalib\src\anomalib\models\components\base\anomaly_module.py", line 179, in _collect_outputs
    image_metric.update(output["pred_scores"], output["label"].int())
  File "C:\Users\Rama.Reddy\Downloads\defect\anomalib\src\anomalib\utils\metrics\collection.py", line 26, in update
    super().update(*args, **kwargs)
  File "c:\Users\Rama.Reddy\Anaconda3\envs\hand\lib\site-packages\torchmetrics\collections.py", line 156, in update
    self._merge_compute_groups()
  File "c:\Users\Rama.Reddy\Anaconda3\envs\hand\lib\site-packages\torchmetrics\collections.py", line 171, in _merge_compute_groups
    metric1 = getattr(self, cg_members1[0])
  File "c:\Users\Rama.Reddy\Anaconda3\envs\hand\lib\site-packages\torch\nn\modules\module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'AnomalibMetricCollection' object has no attribute 'image_F1Score'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
I am unable to reproduce this. When I change the `category` to `leather` from the original config file, I can train a model. Here is the config file I used. 

```yaml

dataset:
  name: mvtec
  format: mvtec
  path: ./datasets/MVTec
  category: leather
  task: segmentation
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: padim
  backbone: resnet18
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null # options: torch, onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

**Comment by kumarsyamala** [comment]
> I am unable to reproduce this. When I change the `category` to `leather` from the original config file, I can train a model. Here is the config file I used.
> 
> ```yaml
> dataset:
>   name: mvtec
>   format: mvtec
>   path: ./datasets/MVTec
>   category: leather
>   task: segmentation
>   train_batch_size: 32
>   eval_batch_size: 32
>   num_workers: 8
>   image_size: 256 # dimensions to which images are resized (mandatory)
>   center_crop: null # dimensions to which images are center-cropped after resizing (optional)
>   normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
>   transform_config:
>     train: null
>     eval: null
>   test_split_mode: from_dir # options: [from_dir, synthetic]
>   test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
>   val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
>   val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
>   tiling:
>     apply: false
>     tile_size: null
>     stride: null
>     remove_border_count: 0
>     use_random_tiling: False
>     random_tile_count: 16
> 
> model:
>   name: padim
>   backbone: resnet18
>   pre_trained: true
>   layers:
>     - layer1
>     - layer2
>     - layer3
>   normalization_method: min_max # options: [none, min_max, cdf]
> 
> metrics:
>   image:
>     - F1Score
>     - AUROC
>   pixel:
>     - F1Score
>     - AUROC
>   threshold:
>     method: adaptive #options: [adaptive, manual]
>     manual_image: null
>     manual_pixel: null
> 
> visualization:
>   show_images: False # show images on the screen
>   save_images: True # save images to the file system
>   log_images: True # log images to the available loggers (if any)
>   image_save_path: null # path to which images will be saved
>   mode: full # options: ["full", "simple"]
> 
> project:
>   seed: 42
>   path: ./results
> 
> logging:
>   logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
>   log_graph: false # Logs the model graph to respective logger.
> 
> optimization:
>   export_mode: null # options: torch, onnx, openvino
> 
> # PL Trainer Args. Don't add extra parameter here.
> trainer:
>   enable_checkpointing: true
>   default_root_dir: null
>   gradient_clip_val: 0
>   gradient_clip_algorithm: norm
>   num_nodes: 1
>   devices: 1
>   enable_progress_bar: true
>   overfit_batches: 0.0
>   track_grad_norm: -1
>   check_val_every_n_epoch: 1 # Don't validate before extracting features.
>   fast_dev_run: false
>   accumulate_grad_batches: 1
>   max_epochs: 1
>   min_epochs: null
>   max_steps: -1
>   min_steps: null
>   max_time: null
>   limit_train_batches: 1.0
>   limit_val_batches: 1.0
>   limit_test_batches: 1.0
>   limit_predict_batches: 1.0
>   val_check_interval: 1.0 # Don't validate before extracting features.
>   log_every_n_steps: 50
>   accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
>   strategy: null
>   sync_batchnorm: false
>   precision: 32
>   enable_model_summary: true
>   num_sanity_val_steps: 0
>   profiler: null
>   benchmark: false
>   deterministic: false
>   reload_dataloaders_every_n_epochs: 0
>   auto_lr_find: false
>   replace_sampler_ddp: true
>   detect_anomaly: false
>   auto_scale_batch_size: false
>   plugins: null
>   move_metrics_to_cpu: false
>   multiple_trainloader_mode: max_size_cycle
> ```

hey hi 

I am not sure why this is happening though, I tried with different formats of the dataset and different models also , I am getting the same error 

You can refer this discussion which I started, Here I am trying train the model with custom dataset https://github.com/openvinotoolkit/anomalib/discussions/1117#discussion-5281049

**Comment by samet-akcay** [comment]
@kumarsyamala, I cannot reproduce this. Using your configuration file I can train a model. Can you confirm you install anomalib on a freshly created virtual environment to ensure you are using the right anomalib version?

For the time being, I'm converting this to a Q&A since this is not an issue.
