### ISSUE TITLE
[Bug]: Could not find the 'LightningModule' attribute for the 'torchmetrics.Metric' logged when using DRAEM

### ISSUE THREAD

**Issue by phcarval** [openvinotoolkit/anomalib#1134]
### Describe the bug

When using the DRAEM model through the following command:

`python3 tools/train.py --config src/anomalib/models/draem/config.yaml`

without changing anything but the train and val batch sizes in the configuration file, and letting it train and validate for one epoch, and pressing "CTRL+C" to end training, it ends testing with this error message:

`lightning_fabric.utilities.exceptions.MisconfigurationException: Could not find the ``LightningModule`` attribute for the ``torchmetrics.Metric`` logged. You can fix this by calling ``self.log(pixel_F1Score, ..., metric_attribute=name)`` where ``name`` is one of ['image_threshold', 'pixel_threshold', 'image_metrics.F1Score', 'image_metrics.AUROC', 'pixel_metrics.F1Score', 'pixel_metrics.AUROC', 'normalization_metrics']`

For some reason, other config files don't return with error (but I also didn't need to change the batch sizes).

### Dataset

MVTec

### Model

DRAEM

### Steps to reproduce the behavior

1. Install anomalib: git clone https://github.com/openvinotoolkit/anomalib/
2. cd anomalib
3. Open VSCode
4. Open in container
5. python3 tools/train.py --config src/anomalib/models/draem/config.yaml

### OS information

OS information:
- OS: Ubuntu 20.04 + Linux Mint 21.1
- Python version: 3.10.10

### Expected behavior

Testing doesn't end with an error

### Pip/GitHub

GitHub

### What version/branch did you use?

main, commit 4b45f0587425d1166b5c2b3e19735c89b2353718

### Configuration YAML

```yaml
dataset:
  name: mvtec
  format: mvtec
  path: ./datasets/MVTec
  category: bottle
  task: segmentation
  train_batch_size: 4
  eval_batch_size: 4
  num_workers: 8
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: draem
  anomaly_source_path: null # optional, e.g. ./datasets/dtd
  lr: 0.0001
  enable_sspcab: false
  sspcab_lambda: 0.1
  early_stopping:
    patience: 20
    metric: pixel_AUROC
    mode: max
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null # options: torch, onnx, openvino
# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 700
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

### Logs

```shell
python3 tools/train.py --config src/anomalib/models/draem/config.yaml 
To use wandb logger install it using `pip install wandb`
/workspaces/anomalib/src/anomalib/config/config.py:275: UserWarning: config.project.unique_dir is set to False. This does not ensure that your results will be written in an empty directory and you may overwrite files.
  warn(
Global seed set to 42
2023-06-15 13:27:10,994 - anomalib.data - INFO - Loading the datamodule
2023-06-15 13:27:10,995 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2023-06-15 13:27:11,083 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2023-06-15 13:27:11,083 - anomalib.models - INFO - Loading the model.
2023-06-15 13:27:11,083 - anomalib.models.components.base.anomaly_module - INFO - Initializing DraemLightning model.
/home/user/conda/lib/python3.10/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
2023-06-15 13:27:11,796 - anomalib.utils.loggers - INFO - Loading the experiment logger(s)
2023-06-15 13:27:11,796 - anomalib.utils.callbacks - INFO - Loading the callbacks
/workspaces/anomalib/src/anomalib/utils/callbacks/__init__.py:142: UserWarning: Export option: None not found. Defaulting to no model export
  warnings.warn(f"Export option: {config.optimization.export_mode} not found. Defaulting to no model export")
2023-06-15 13:27:11,809 - pytorch_lightning.utilities.rank_zero - INFO - GPU available: True (cuda), used: True
2023-06-15 13:27:11,809 - pytorch_lightning.utilities.rank_zero - INFO - TPU available: False, using: 0 TPU cores
2023-06-15 13:27:11,809 - pytorch_lightning.utilities.rank_zero - INFO - IPU available: False, using: 0 IPUs
2023-06-15 13:27:11,809 - pytorch_lightning.utilities.rank_zero - INFO - HPU available: False, using: 0 HPUs
2023-06-15 13:27:11,810 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
2023-06-15 13:27:11,810 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
2023-06-15 13:27:11,810 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_test_batches=1.0)` was configured so 100% of the batches will be used..
2023-06-15 13:27:11,810 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_predict_batches=1.0)` was configured so 100% of the batches will be used..
2023-06-15 13:27:11,810 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
2023-06-15 13:27:11,810 - anomalib - INFO - Training the model.
2023-06-15 13:27:11,962 - anomalib.data.mvtec - INFO - Found the dataset.
/home/user/conda/lib/python3.10/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `ROC` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:613: UserWarning: Checkpoint directory /workspaces/anomalib/results/draem/mvtec/bottle/run/weights/lightning exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
2023-06-15 13:27:13,019 - pytorch_lightning.accelerators.cuda - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2023-06-15 13:27:13,025 - pytorch_lightning.callbacks.model_summary - INFO - 
  | Name                  | Type                     | Params
-------------------------------------------------------------------
0 | image_threshold       | AnomalyScoreThreshold    | 0     
1 | pixel_threshold       | AnomalyScoreThreshold    | 0     
2 | model                 | DraemModel               | 97.4 M
3 | loss                  | DraemLoss                | 0     
4 | image_metrics         | AnomalibMetricCollection | 0     
5 | pixel_metrics         | AnomalibMetricCollection | 0     
6 | normalization_metrics | MinMax                   | 0     
-------------------------------------------------------------------
97.4 M    Trainable params
0         Non-trainable params
97.4 M    Total params
389.691   Total estimated model params size (MB)
Epoch 0:   0%|                                                                                                                                        | 0/74 [00:00<?, ?it/s]/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/core/module.py:493: UserWarning: You called `self.log('train_loss', ..., logger=True)` but have no logger configured. You can enable one by doing `Trainer(logger=ALogger(...))`
  rank_zero_warn(
/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py:83: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 4. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  warning_cache.warn(
Epoch 0:  70%|█████████████████████████████████████████████████████████████████▎                           | 52/74 [00:53<00:22,  1.03s/it, loss=0.64, train_loss_step=0.603]/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py:83: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 1. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  warning_cache.warn(
Epoch 4:  66%|███████████████████▏         | 49/74 [00:49<00:25,  1.02s/it, loss=0.35, train_loss_step=0.323, pixel_F1Score=0.412, pixel_AUROC=0.685, train_loss_epoch=0.341]^C/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py:48: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...               
  rank_zero_warn("Detected KeyboardInterrupt, attempting graceful shutdown...")
2023-06-15 13:32:16,713 - anomalib - INFO - Loading the best model weights.
2023-06-15 13:32:16,713 - anomalib - INFO - Testing the model.
2023-06-15 13:32:16,719 - pytorch_lightning.utilities.rank_zero - INFO - The following callbacks returned in `LightningModule.configure_callbacks` will override existing callbacks passed to Trainer: EarlyStopping
2023-06-15 13:32:16,720 - anomalib.data.mvtec - INFO - Found the dataset.
2023-06-15 13:32:16,720 - anomalib.utils.callbacks.model_loader - INFO - Loading the model from /workspaces/anomalib/results/draem/mvtec/bottle/run/weights/lightning/model-v4.ckpt
2023-06-15 13:32:17,365 - pytorch_lightning.accelerators.cuda - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Testing DataLoader 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21/21 [00:48<00:00,  2.30s/it]Traceback (most recent call last):
  File "/workspaces/anomalib/tools/train.py", line 79, in <module>
    train(args)
  File "/workspaces/anomalib/tools/train.py", line 74, in train
    trainer.test(model=model, datamodule=datamodule)
  File "/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 794, in test
    return call._call_and_handle_interrupt(
  File "/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 842, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1188, in _run_stage
    return self._run_evaluate()
  File "/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1228, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 206, in run
    output = self.on_run_end()
  File "/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 180, in on_run_end
    self._evaluation_epoch_end(self._outputs)
  File "/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 288, in _evaluation_epoch_end
    self.trainer._call_lightning_module_hook(hook_name, output_or_outputs)
  File "/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1356, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/workspaces/anomalib/src/anomalib/models/components/base/anomaly_module.py", line 156, in test_epoch_end
    self._log_metrics()
  File "/workspaces/anomalib/src/anomalib/models/components/base/anomaly_module.py", line 223, in _log_metrics
    self.log_dict(self.pixel_metrics, prog_bar=True)
  File "/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 583, in log_dict
    self.log(
  File "/home/user/conda/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 477, in log
    raise MisconfigurationException(
lightning_fabric.utilities.exceptions.MisconfigurationException: Could not find the `LightningModule` attribute for the `torchmetrics.Metric` logged. You can fix this by calling `self.log(pixel_F1Score, ..., metric_attribute=name)` where `name` is one of ['image_threshold', 'pixel_threshold', 'image_metrics.F1Score', 'image_metrics.AUROC', 'pixel_metrics.F1Score', 'pixel_metrics.AUROC', 'normalization_metrics']
Epoch 4:  66%|██████▌   | 49/74 [01:41<00:51,  2.07s/it, loss=0.35, train_loss_step=0.323, pixel_F1Score=0.412, pixel_AUROC=0.685, train_loss_epoch=0.341]                   
Testing DataLoader 0: 100%|██████████| 21/21 [00:49<00:00,  2.36s/it]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mykappa** [comment]
@phcarval Did you find the reason for this?
