### ISSUE TITLE
Wandb sweep error

### ISSUE THREAD

**Issue by NaiyerRafique** [openvinotoolkit/anomalib#1184]
### What is the motivation for this task?

I try to run the wandb sweep and with my custom data. I ran successfully in the past but now it shows some errors

I get the following error:

```python
/content/drive/MyDrive/anomalib/src/anomalib/config/config.py:280: UserWarning: config.project.unique_dir is set to False. This does not ensure that your results will be written in an empty directory and you may overwrite files.
  warn(
Global seed set to 42
Create sweep with ID: 4muan007
Sweep URL: https://wandb.ai/#######/draem_unscaled_dataset_smooth_cropped/sweeps/4muan007
wandb: Agent Starting Run: 1ogdv5yp with config:
wandb: 	dataset.image_size: 128
wandb: 	model.backbone: resnet18
wandb: Currently logged in as: ###########(########). Use `wandb login --relogin` to force relogin
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
Problem at: /usr/local/lib/python3.10/dist-packages/pytorch_lightning/loggers/wandb.py 405 experiment
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 611, in init
    run = Run(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 535, in __init__
    self._init(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 650, in _init
    self._config._update(config, ignore_locked=True)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_config.py", line 237, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_config.py", line 255, in _sanitize
    val = json_friendly_val(val)
  File "/usr/local/lib/python3.10/dist-packages/wandb/util.py", line 653, in json_friendly_val
    converted = asdict(val)
  File "/usr/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/usr/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/usr/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
wandb: ERROR Run 1ogdv5yp errored: Error('An unexpected error occurred')
wandb: Agent Starting Run: 8fzqy4b1 with config:
wandb: 	dataset.image_size: 128
wandb: 	model.backbone: wide_resnet50_2
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
Problem at: /usr/local/lib/python3.10/dist-packages/pytorch_lightning/loggers/wandb.py 405 experiment
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 611, in init
    run = Run(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 535, in __init__
    self._init(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 650, in _init
    self._config._update(config, ignore_locked=True)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_config.py", line 237, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_config.py", line 255, in _sanitize
    val = json_friendly_val(val)
  File "/usr/local/lib/python3.10/dist-packages/wandb/util.py", line 653, in json_friendly_val
    converted = asdict(val)
  File "/usr/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/usr/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/usr/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
wandb: ERROR Run 8fzqy4b1 errored: Error('An unexpected error occurred')
wandb: Agent Starting Run: brgql58y with config:
wandb: 	dataset.image_size: 256
wandb: 	model.backbone: resnet18
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
Problem at: /usr/local/lib/python3.10/dist-packages/pytorch_lightning/loggers/wandb.py 405 experiment
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 611, in init
    run = Run(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 535, in __init__
    self._init(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 650, in _init
    self._config._update(config, ignore_locked=True)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_config.py", line 237, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_config.py", line 255, in _sanitize
    val = json_friendly_val(val)
  File "/usr/local/lib/python3.10/dist-packages/wandb/util.py", line 653, in json_friendly_val
    converted = asdict(val)
  File "/usr/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/usr/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/usr/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
wandb: ERROR Run brgql58y errored: Error('An unexpected error occurred')
wandb: ERROR Detected 3 failed runs in the first 60 seconds, killing sweep.
wandb: To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true

``` 
 I use the following wandb sweep file:

```
observation_budget: 16
method: grid
metric:
  name: pixel_F1Score
  goal: maximize
parameters:
  dataset:
    category: unscaled_dataset
    image_size:
      values: [128, 256, 384, 512, 640, 768]
  model:
    backbone:
      values: [resnet18, wide_resnet50_2]
```

I change the dataset section of the config file as follows:
```
dataset:
  name: unscaled_dataset_smooth_cropped
  format: folder
  path: /content/drive/MyDrive/unscaled_dataset_smooth_cropped
  normal_dir: /content/drive/MyDrive/unscaled_dataset_smooth_cropped/train
  abnormal_dir: /content/drive/MyDrive/unscaled_dataset_smooth_cropped/test/hard_damaged
  normal_test_dir: /content/drive/MyDrive/unscaled_dataset_smooth_cropped/test/normal
  task: segmentation # classification or segmentation
  mask: /content/drive/MyDrive/unscaled_dataset_smooth_cropped/ground_truth/hard_damaged
  extensions: ".png"
  normalization: imagenet
  split_ratio: 0.2 # ratio of the normal images that will be used to create a test split
  image_size: 640
  train_batch_size: 2
  test_batch_size: 1
  num_workers: 2
  transform_config:
    train: null
    val: null
  test_split_mode: from_dir
  val_split_ratio: 0.5
  create_validation_set: false
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
```

### Describe the solution you'd like

I simply want to know how to fix the error so I can run the sweep successfully

### Additional context

It was working before but now there suddenly the sweep error comes up. Please inform me if more information is needed and how to fix this.

**Comment by blaz-r** [comment]
Hello. I think the issue is that you have a version of wandb that is too recent. Inside requirements `wandb==0.12.17` is listed. I believe that if you install this version, it should work again.

**Comment by samet-akcay** [comment]
> Hello. I think the issue is that you have a version of wandb that is too recent. Inside requirements `wandb==0.12.17` is listed. I believe that if you install this version, it should work again.

@NaiyerRafique have you tried this?
