### ISSUE TITLE
[Bug]: RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

### ISSUE THREAD

**Issue by Mozihua** [openvinotoolkit/anomalib#1237]
### Describe the bug

trying to use TorchInferencer in a new process (created by myself), but report a bug: RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

### Dataset

MVTec

### Model

PatchCore

### Steps to reproduce the behavior

1. import TorchInferencer
2. create  a new process by myself
3. In this process,  use TorchInferencer to load a model.pt which exported by torch model
3. see error: RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

### OS information

OS information:
- OS: [Ubuntu 16.04]
- Python version: [3.7.12]
- Anomalib version: [0.5.0]
- PyTorch version: [1.13.1+cu117]
- CUDA/cuDNN version: [9.0.176]
- GPU models and configuration: [1x NVIDIA GeForce RTX 2080 Ti]
- Any other relevant information: [I'm using a my own dataset]

### Expected behavior

I hope to use PatchCore model to classify ok or ng in a process created by myself

### Screenshots

import os
from multiprocessing import Process
from anomalib.deploy import TorchInferencer
import torch

def get_model():
    model_path = 'model.pt'
    torch.set_grad_enabled(False)
    model = TorchInferencer(path=model_path, device='gpu')

if __name__ == '__main__':
    p_one = Process(target=get_model)
    p_one.start()
    print("son:%s  father:%s" % (os.getpid(), os.getppid()))

### Pip/GitHub

pip

### What version/branch did you use?

0.5.0

### Configuration YAML

```yaml
dataset:
  name: mydata_exp
  format: mvtec
  path: MVTec_style
  task: segmentation
  category: mydata
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 8
  image_size: 128 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: from_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: patchcore
  backbone: wide_resnet50_2
  pre_trained: true
  layers:
    - layer2
    - layer3
  coreset_sampling_ratio: 0.1
  num_neighbors: 9
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 0
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
#  export_mode: null # options: onnx, openvino
  export_mode: torch # options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: gpu # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

### Logs

```shell
/home/mm/anaconda3/envs/AST_clone/bin/python /test4.py
son:14724  father:4018
Process Process-1:
Traceback (most recent call last):
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/test4.py", line 9, in get_model
    model = TorchInferencer(path=model_path, device='gpu')
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/anomalib/deploy/inferencers/torch_inferencer.py", line 40, in __init__
    self.model = self.load_model(path)
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/anomalib/deploy/inferencers/torch_inferencer.py", line 94, in load_model
    model = torch.load(path, map_location=self.device)["model"]
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/pickle.py", line 1129, in load_binpersid
    self.append(self.persistent_load(pid))
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/serialization.py", line 1055, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/serialization.py", line 163, in validate_cuda_device
    device = torch.cuda._utils._get_device_index(location, True)
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/cuda/_utils.py", line 34, in _get_device_index
    return _torch_get_device_index(device, optional, allow_cpu)
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/_utils.py", line 628, in _get_device_index
    device_idx = _get_current_device_index()
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/_utils.py", line 567, in _get_current_device_index
    return _get_device_attr(lambda m: m.current_device())
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/_utils.py", line 558, in _get_device_attr
    return get_member(torch.cuda)
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/_utils.py", line 567, in <lambda>
    return _get_device_attr(lambda m: m.current_device())
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/cuda/__init__.py", line 552, in current_device
    _lazy_init()
  File "/home/mm/anaconda3/envs/AST_clone/lib/python3.7/site-packages/torch/cuda/__init__.py", line 218, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. To use CUDA with "
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

Process finished with exit code 0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mozihua** [comment]
I am sorry to submit this issue without trying enough, i found that configuring the start_method of process can solved it. Thank you very much!

**Comment by samet-akcay** [comment]
@Mozihua, no worries. Good to hear that you resolved your issue!
