### ISSUE TITLE
ValueError: Unknown model efficient_ad!

### ISSUE THREAD

**Issue by zzh805780186** [openvinotoolkit/anomalib#1244]
Hi~ ,  How to resole this problem that i met :

python tools/train.py --model efficient_ad
/home/xxx/anaconda3/envs/anomalib_env/lib/python3.8/site-packages/anomalib/config/config.py:275: UserWarning: config.project.unique_dir is set to False. This does not ensure that your results will be written in an empty directory and you may overwrite files.
  warn(
Global seed set to 42
2023-08-08 13:55:11,074 - anomalib.data - INFO - Loading the datamodule
2023-08-08 13:55:11,075 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2023-08-08 13:55:11,075 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2023-08-08 13:55:11,075 - anomalib.models - INFO - Loading the model.
Traceback (most recent call last):
  File "tools/train.py", line 79, in <module>
    train(args)
  File "tools/train.py", line 58, in train
    model = get_model(config)
  File "/home/xxx/anaconda3/envs/anomalib_env/lib/python3.8/site-packages/anomalib/models/__init__.py", line 103, in get_model
    raise ValueError(f"Unknown model {config.model.name}!")
ValueError: Unknown model efficient_ad!

**Comment by blaz-r** [comment]
Hello, judging by the line of error, I think you are using an older version of code. Did you follow the installation procedure here:
https://github.com/openvinotoolkit/anomalib#getting-started

**Comment by samet-akcay** [comment]
@zzh805780186, can you share the following from your python terminal?

```python
>>> import anomalib
>>> anomalib.__version__
```

**Comment by zzh805780186** [comment]
> Hello, judging by the line of error, I think you are using an older version of code. Did you follow the installation procedure here: https://github.com/openvinotoolkit/anomalib#getting-started

Thanks you. I download the newest version of code , and resolve this problem.
