### ISSUE TITLE
[Bug]: padim unable to export  the openvino model

### ISSUE THREAD

**Issue by kikyostudypython** [openvinotoolkit/anomalib#1282]
### Describe the bug

i set export_mode to openvino and get error.

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

python tools/train.py --model padim

### OS information

OS: [windows 10]
Python version: [3.8]
Anomalib version: [1.0.0]
PyTorch version: [torch | 1.12.1+cu116]
CUDA/cuDNN version: [Build cuda_11.2.r11.2/compiler.29373293_0]
GPU models and configuration: [NVIDIA GeForce RTX 3060]
Any other relevant information: [I'm using mvtec/bottle dataset]

### Expected behavior

i want to get the openvino model

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
dataset:
  name: mvtec
  format: mvtec
  path: ./datasets/MVTec
  category: bottle
  task: segmentation
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 1
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: padim
  backbone: resnet18
  pre_trained: true
  layers:
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: openvino # options: torch, onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

### Logs

```shell
PS D:\Project\anomalib-main> python tools/train.py --model padim
D:\Project\anomalib-main\anomalib\config\config.py:275: UserWarning: config.project.unique_dir is set to False. This does not ensure that your results will be written in an empty directory and you may overwrite files.
  warn(
Global seed set to 42
2023-08-18 17:11:58,870 - anomalib.data - INFO - Loading the datamodule
2023-08-18 17:11:58,870 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2023-08-18 17:11:58,870 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2023-08-18 17:11:58,870 - anomalib.models - INFO - Loading the model.
2023-08-18 17:11:58,874 - anomalib.models.components.base.anomaly_module - INFO - Initializing PadimLightning model.
E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory fo
otprint.
  warnings.warn(*args, **kwargs)
2023-08-18 17:11:58,878 - anomalib.models.components.feature_extractors.timm - WARNING - FeatureExtractor is deprecated. Use TimmFeatureExtractor instead. Both FeatureExtractor and TimmFeatureExtractor will be removed in a future relea
se.
2023-08-18 17:11:59,106 - timm.models.helpers - INFO - Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
2023-08-18 17:11:59,290 - anomalib.utils.loggers - INFO - Loading the experiment logger(s)
2023-08-18 17:11:59,290 - anomalib.utils.callbacks - INFO - Loading the callbacks
2023-08-18 17:11:59,294 - anomalib.utils.callbacks - INFO - Setting model export to openvino
2023-08-18 17:11:59,362 - pytorch_lightning.utilities.rank_zero - INFO - GPU available: True (cuda), used: True
2023-08-18 17:11:59,362 - pytorch_lightning.utilities.rank_zero - INFO - TPU available: False, using: 0 TPU cores
2023-08-18 17:11:59,362 - pytorch_lightning.utilities.rank_zero - INFO - IPU available: False, using: 0 IPUs
2023-08-18 17:11:59,362 - pytorch_lightning.utilities.rank_zero - INFO - HPU available: False, using: 0 HPUs
2023-08-18 17:11:59,362 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
2023-08-18 17:11:59,362 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
2023-08-18 17:11:59,362 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_test_batches=1.0)` was configured so 100% of the batches will be used..
2023-08-18 17:11:59,362 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_predict_batches=1.0)` was configured so 100% of the batches will be used..
2023-08-18 17:11:59,362 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
2023-08-18 17:11:59,362 - anomalib - INFO - Training the model.
2023-08-18 17:11:59,370 - anomalib.data.mvtec - INFO - Found the dataset.....
2023-08-18 17:11:59,370 - pytorch_lightning.utilities.rank_zero - INFO - You are using a CUDA device ('NVIDIA GeForce RTX 3060') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('mediu
m' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: Metric `ROC` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:613: UserWarning: Checkpoint directory D:\Project\anomalib-main\results\padim\mvtec\bottle\run\weights exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
2023-08-18 17:11:59,548 - pytorch_lightning.accelerators.cuda - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\pytorch_lightning\core\optimizer.py:183: UserWarning: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer
  rank_zero_warn(
2023-08-18 17:11:59,552 - pytorch_lightning.callbacks.model_summary - INFO -
  | Name                  | Type                     | Params
-------------------------------------------------------------------
0 | image_threshold       | AnomalyScoreThreshold    | 0
1 | pixel_threshold       | AnomalyScoreThreshold    | 0
2 | model                 | PadimModel               | 2.8 M
3 | image_metrics         | AnomalibMetricCollection | 0
4 | pixel_metrics         | AnomalibMetricCollection | 0
5 | normalization_metrics | MinMax                   | 0
-------------------------------------------------------------------
2.8 M     Trainable params
0         Non-trainable params
2.8 M     Total params
11.131    Total estimated model params size (MB)
E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider in
creasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider in
creasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 0:   0%|                                                                                                                                                                                                     | 0/10 [00:00<?, ?it/s]E
:\AnacondaInstall\envs\anomalib_env\lib\site-packages\pytorch_lightning\loops\optimization\optimizer_loop.py:138: UserWarning: `training_step` returned `None`. If this was on purpose, ignore this warning...
  self.warning_cache.warn("`training_step` returned `None`. If this was on purpose, ignore this warning...")
Epoch 0:  70%|████████████████2023-08-18 17:12:11,404 - anomalib.models.padim.lightning_model - INFO - Aggregating the embedding extracted from the training set.                                | 7/10 [00:10<00:04,  1.55s/it, loss=nan] 
2023-08-18 17:12:11,408 - anomalib.models.padim.lightning_model - INFO - Fitting a Gaussian to the embedding collected from the training set.
Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:19<00:00,  1.93s/it, loss=nan, pixel_F1Score=0.650, pixel_AUROC=0.977]2
023-08-18 17:12:19,907 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer.fit` stopped: `max_epochs=1` reached.
2023-08-18 17:12:19,907 - anomalib.utils.callbacks.export - INFO - Exporting the model
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Traceback (most recent call last):
  File "tools/train.py", line 81, in <module>
    train(args)
  File "tools/train.py", line 66, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1112, in _run
    results = self._run_stage()
  File "E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1191, in _run_stage
    self._run_train()
  File "E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\pytorch_lightning\loops\loop.py", line 206, in run
    output = self.on_run_end()
  File "E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 323, in on_run_end
    self.trainer._call_callback_hooks("on_train_end")
  File "E:\AnacondaInstall\envs\anomalib_env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1394, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "D:\Project\anomalib-main\anomalib\utils\callbacks\export.py", line 46, in on_train_end
    export(
  File "D:\Project\anomalib-main\anomalib\deploy\export.py", line 116, in export
    export_to_openvino(export_path, onnx_path)
  File "D:\Project\anomalib-main\anomalib\deploy\export.py", line 167, in export_to_openvino
    subprocess.run(optimize_command, check=True)  # nosec
  File "E:\AnacondaInstall\envs\anomalib_env\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\AnacondaInstall\envs\anomalib_env\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\AnacondaInstall\envs\anomalib_env\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system could not find the file。
Epoch 0: 100%|██████████| 10/10 [00:21<00:00,  2.14s/it, loss=nan, pixel_F1Score=0.650, pixel_AUROC=0.977]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@ashwinvaidya17, can you try to reproduce this on your windows machine?

**Comment by ashwinvaidya17** [comment]
@kikyostudypython I tried it on my machine and the export is working fine. Can you try it agian on a fresh environment?

**Comment by samet-akcay** [comment]
Closing this due to inactivity. Feel free to re-open if you still have this issue.

**Comment by concrete13377** [comment]
same problem both conda and pip installation
