### ISSUE TITLE
[Bug]: CI failed at pytest

### ISSUE THREAD

**Issue by thinhngo-x** [openvinotoolkit/anomalib#1820]
### Describe the bug

When submitting a PR, the Pre-Merge checks failed and raised an error:
`ImportError: cannot import name 'call_runtest_hook' from '_pytest.runner' (/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/_pytest/runner.py)`.

This could be due to the conflict between the new release of `pytest` and `flaky` as reported in https://github.com/box/flaky/issues/198.

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

1. Fork, clone, and install Anomalib repo.
2. Make some changes.
3. Submit a PR.
4. Wait for the Pre-Merge check to run and observe the logs.

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

The Pre-Merge checks failed when `pytest` started.

### Pip/GitHub

pip

### Configuration YAML

```yaml
N/A
```

### Logs
https://github.com/openvinotoolkit/anomalib/actions/runs/8115814696/job/22247550749#step:6:68
```shell
pre-merge-py310: commands[0]> pytest tests/integration tests/unit --cov=anomalib --cov-report=xml:/home/user/actions-runner/_work/anomalib/anomalib/.tox/coverage.xml --cov-fail-under=75
Traceback (most recent call last):
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/_pytest/config/__init__.py", line 195, in console_main
    code = main()
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/_pytest/config/__init__.py", line 153, in main
    config = _prepareconfig(args, plugins)
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/_pytest/config/__init__.py", line 335, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/pluggy/_callers.py", line 121, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
    config = yield
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1141, in pytest_cmdline_parse
    self.parse(args)
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1490, in parse
    self._preparse(args, addopts=addopts)
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1377, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/pluggy/_manager.py", line 414, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/user/actions-runner/_work/_tool/Python/3.10.13/x64/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/user/actions-runner/_work/_tool/Python/3.10.13/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/flaky/flaky_pytest_plugin.py", line 5, in <module>
    from _pytest.runner import call_runtest_hook  # pylint:disable=import-error
ImportError: cannot import name 'call_runtest_hook' from '_pytest.runner' (/home/user/actions-runner/_work/anomalib/anomalib/.tox/pre-merge-py310/lib/python3.10/site-packages/_pytest/runner.py)
pre-merge-py310: exit 1 (0.41 seconds) /home/user/actions-runner/_work/anomalib/anomalib> pytest tests/integration tests/unit --cov=anomalib --cov-report=xml:/home/user/actions-runner/_work/anomalib/anomalib/.tox/coverage.xml --cov-fail-under=75 pid=5473
.pkg: _exit> python /home/user/actions-runner/_work/_tool/Python/3.10.13/x64/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  pre-merge-py310: FAIL code 1 (129.83=setup[129.42]+cmd[0.41] seconds)
  evaluation failed :( (130.07 seconds)
Error: Process completed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thinhngo-x** [comment]
Seems like the issue has been resolved from the side of `flaky` https://github.com/plotly/dash/pull/2806
