### ISSUE TITLE
[Bug]: Device with "gpu" name is not registered in the OpenVINO Runtime

### ISSUE THREAD

**Issue by haimat** [openvinotoolkit/anomalib#2119]
### Describe the bug

I run this code:

```python
import openvino as ov
core = ov.Core()
print(core.available_devices)
inferencer = OpenVINOInferencer(path="/path/to/model.onnx", device="gpu")
```

The output is this:

> ['CPU', 'GPU.0', 'GPU.1', 'GPU.2', 'GPU.3']

Which seems correct, as I have 4 GPUs in this machine.
Now I want to run an ONNX model trained with **openvinotoolkit/anomalib** on the GPU (last line above):

```
Traceback (most recent call last):
  File "/data/scratch/mkw-anomalib/anomalib-predict.py", line 27, in <module>
    inferencer = OpenVINOInferencer(path="/path/to/model.onnx", device="gpu")
  File "/home/sinntelligence/.local/lib/python3.10/site-packages/anomalib/deploy/inferencers/openvino_inferencer.py", line 109, in __init__
    self.input_blob, self.output_blob, self.model = self.load_model(path)
  File "/home/sinntelligence/.local/lib/python3.10/site-packages/anomalib/deploy/inferencers/openvino_inferencer.py", line 147, in load_model
    compile_model = core.compile_model(model=model, device_name=self.device, config=self.config)
  File "/home/sinntelligence/.local/lib/python3.10/site-packages/openvino/runtime/ie_api.py", line 521, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Exception from src/inference/src/cpp/core.cpp:106:
Exception from src/inference/src/dev/core_impl.cpp:566:
Device with "gpu" name is not registered in the OpenVINO Runtime
```

Any ideas what could be the issue here?

### Dataset

Other (please specify in the text field below)

### Model

Other (please specify in the field below)

### Steps to reproduce the behavior

1. Install anomalib and deps
2. Run code listed above

### OS information

OS information:
- OS: Ubuntu 22.04
- Python version: 3.10.12
- Anomalib version: 1.1.0
- PyTorch version: 2.2.2+cu121
- CUDA/cuDNN version: 12.2
- GPU models and configuration: 4x Nvidia RTX A6000
- Trained model: Fastflow

### Expected behavior

I was expecting the anomalib to support the GPU, since `core.available_devices` shows all of my 4 GPUs.

### Pip/GitHub

pip

### What version/branch did you use?

1.1.0

### Configuration YAML

```yaml
(where do I find this YAML config?)
```

### Logs

```shell
No logs beside the console output above.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by haimat** [comment]
Found the solution: I had to use "GPU", not "gpu" (case sensitive).
https://github.com/openvinotoolkit/openvino/issues/24913#issuecomment-2155808965
