### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'train'

### ISSUE THREAD

**Issue by LukasBommes** [openvinotoolkit/anomalib#219]
Currently, I encounter the following error when running `tools/train.py` with a custom folder dataset and `transform_config: null` set in the config.

```
Traceback (most recent call last):
  File "tools/train.py", line 71, in <module>
    train()
  File "tools/train.py", line 54, in train
    datamodule = get_datamodule(config)
  File "/anomalib/anomalib/data/__init__.py", line 83, in get_datamodule
    transform_config_train=config.dataset.transform_config.train,
AttributeError: 'NoneType' object has no attribute 'train'
```

The config is as follows:
```
dataset:
  name: pv_fault_single_patch_per_module_converted_small
  format: folder
  path: ./datasets/pv_fault_single_patch_per_module_converted_small
  normal: normal
  abnormal: abnormal
  task: classification
  mask: null
  extensions: null
  split_ratio: 0.2
  seed: 0  
  image_size: 64 #224
  train_batch_size: 32
  test_batch_size: 1
  num_workers: 16
  transform_config: null
  create_validation_set: true  
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
```
Where the rest corresponds to the default Padim config.

**Comment by alexriedel1** [comment]
you have to update your config.yaml :)

**Comment by LukasBommes** [comment]
Ah, I see. Thanks a lot for clarifying this.
