### ISSUE TITLE
[Bug]: cannot import name '_encode_image' from 'ollama._client'

### ISSUE THREAD

**Issue by zhangjy328** [openvinotoolkit/anomalib#2453]
### Describe the bug

when i run train.py, ImportError: cannot import name '_encode_image' from 'ollama._client'
![error](https://github.com/user-attachments/assets/b7d1d22e-189e-4838-b13f-8065e4fc5284)

### Dataset

Other (please specify in the text field below)

### Model

PatchCore

### Steps to reproduce the behavior

install anomalib use anaconda prompt

### OS information

OS information:
- OS: win10
- Python version: 3.10
- Anomalib version: 1.2.0
- PyTorch version: 2.5.1+cpu
- CUDA/cuDNN version: none
- GPU models and configuration: cpu
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

Traceback (most recent call last):
  File "E:\model\anomalib-main\train.py", line 3, in <module>
    from anomalib.models import Patchcore
  File "E:\model\anomalib-main\src\anomalib\models\__init__.py", line 15, in <module>
    from .image import (
  File "E:\model\anomalib-main\src\anomalib\models\image\__init__.py", line 23, in <module>
    from .vlm_ad import VlmAd
  File "E:\model\anomalib-main\src\anomalib\models\image\vlm_ad\__init__.py", line 6, in <module>
    from .lightning_model import VlmAd
  File "E:\model\anomalib-main\src\anomalib\models\image\vlm_ad\lightning_model.py", line 14, in <module>
    from .backends import Backend, ChatGPT, Huggingface, Ollama
  File "E:\model\anomalib-main\src\anomalib\models\image\vlm_ad\backends\__init__.py", line 9, in <module>
    from .ollama import Ollama
  File "E:\model\anomalib-main\src\anomalib\models\image\vlm_ad\backends\ollama.py", line 23, in <module>
    from ollama._client import _encode_image
ImportError: cannot import name '_encode_image' from 'ollama._client' (C:\Users\zjy\AppData\Local\anaconda3\envs\anomalib_env\lib\site-packages\ollama\_client.py)

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
# Import the required modules
from anomalib.data import MVTec
from anomalib.models import Patchcore
from anomalib.engine import Engine
from anomalib.data import Folder
from anomalib.utils.normalization import NormalizationMethod


# Initialize the datamodule, model and engine
# datamodule = MVTec(num_workers=0)
model = Patchcore()
engine = Engine(
    default_root_dir = './result',
    task = "classification",
    callbacks = None,
    normalization = NormalizationMethod.MIN_MAX,
    threshold = "F1AdaptiveThreshold",
    image_metrics = None,
    pixel_metrics = None,
    logger = None
)

datamodule = Folder(
    name="mvtec",
    root="../datasets/CSP",
    normal_dir="normal",
    abnormal_dir="abnormal",
    task="classification",
    train_batch_size=16,
    eval_batch_size=16,
    num_workers=0,
    image_size=[1024, 1024],
    mask_dir=None,
    normal_split_ratio=0.2,
    seed=None,
)

datamodule.setup()

# Train the model
engine.train(datamodule=datamodule, model=model)
```

### Logs

```shell
Traceback (most recent call last):
  File "E:\model\anomalib-main\train.py", line 3, in <module>
    from anomalib.models import Patchcore
  File "E:\model\anomalib-main\src\anomalib\models\__init__.py", line 15, in <module>
    from .image import (
  File "E:\model\anomalib-main\src\anomalib\models\image\__init__.py", line 23, in <module>
    from .vlm_ad import VlmAd
  File "E:\model\anomalib-main\src\anomalib\models\image\vlm_ad\__init__.py", line 6, in <module>
    from .lightning_model import VlmAd
  File "E:\model\anomalib-main\src\anomalib\models\image\vlm_ad\lightning_model.py", line 14, in <module>
    from .backends import Backend, ChatGPT, Huggingface, Ollama
  File "E:\model\anomalib-main\src\anomalib\models\image\vlm_ad\backends\__init__.py", line 9, in <module>
    from .ollama import Ollama
  File "E:\model\anomalib-main\src\anomalib\models\image\vlm_ad\backends\ollama.py", line 23, in <module>
    from ollama._client import _encode_image
ImportError: cannot import name '_encode_image' from 'ollama._client' (C:\Users\zjy\AppData\Local\anaconda3\envs\anomalib_env\lib\site-packages\ollama\_client.py)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
Looks like the api has changed a bit in ollama. Can you try installing the library as follows: `pip install "llama<0.4"

**Comment by samet-akcay** [comment]
Until we adapt the new API changes, this should work

**Comment by zhangjy328** [comment]
but i have a new question, `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer, and `training_step` returned `None`

C:\Users\zjy\AppData\Local\anaconda3\envs\anomalib_env\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
INFO:anomalib.data.base.datamodule:No normal test images found. Sampling from training set using a split ratio of 0.20
dict_keys(['image_path', 'label', 'image'])
dict_keys(['image_path', 'label', 'image'])
dict_keys(['image_path', 'label', 'image'])
INFO:anomalib.models.components.base.anomaly_module:Initializing Patchcore model.
INFO:timm.models._builder:Loading pretrained weights from Hugging Face hub (timm/wide_resnet50_2.racm_in1k)
INFO:timm.models._hub:[timm/wide_resnet50_2.racm_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
INFO:timm.models._builder:Missing keys (fc.weight, fc.bias) discovered while loading pretrained weights. This is expected if model is being adapted.
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
INFO:anomalib.data.base.datamodule:No normal test images found. Sampling from training set using a split ratio of 0.20
WARNING:anomalib.metrics.f1_score:F1Score class exists for backwards compatibility. It will be removed in v1.1. Please use BinaryF1Score from torchmetrics instead
C:\Users\zjy\AppData\Local\anaconda3\envs\anomalib_env\lib\site-packages\lightning\pytorch\core\optimizer.py:182: **`LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer**

  | Name                  | Type                     | Params | Mode 
---------------------------------------------------------------------------
0 | model                 | PatchcoreModel           | 24.9 M | train
1 | _transform            | Compose                  | 0      | train
2 | normalization_metrics | MetricCollection         | 0      | train
3 | image_threshold       | F1AdaptiveThreshold      | 0      | train
4 | pixel_threshold       | F1AdaptiveThreshold      | 0      | train
5 | image_metrics         | AnomalibMetricCollection | 0      | train
6 | pixel_metrics         | AnomalibMetricCollection | 0      | train
---------------------------------------------------------------------------
24.9 M    Trainable params
0         Non-trainable params
24.9 M    Total params
99.450    Total estimated model params size (MB)
15        Modules in train mode
174       Modules in eval mode
C:\Users\zjy\AppData\Local\anaconda3\envs\anomalib_env\lib\site-packages\lightning\pytorch\trainer\connectors\data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.
C:\Users\zjy\AppData\Local\anaconda3\envs\anomalib_env\lib\site-packages\lightning\pytorch\trainer\connectors\data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.
Epoch 0:   0%|          | 1/250 [00:51<3:35:14,  0.02it/s]C:\Users\zjy\AppData\Local\anaconda3\envs\anomalib_env\lib\site-packages\lightning\pytorch\loops\optimization\automatic.py:132: **`training_step` returned `None`. If this was on purpose, ignore this warning...**

**Comment by samet-akcay** [comment]
Patchcore doesn't have an optimizer, so this is on purpose. As long as you get a val/test score, everything works as expected

**Comment by zhangjy328** [comment]
Thanks, So is everything normal like this? Just wait for it to finish training and produce results?

**Comment by zhangjy328** [comment]
And I also have another question：How can I continue training the model based on the results of the previous training session?

**Comment by neoragex2002** [comment]
> Looks like the api has changed a bit in ollama. Can you try installing the library as follows: `pip install "llama<0.4"`

it is not `pip install "llama<0.4". it is 'pip install "ollama<0.4"....

**Comment by samet-akcay** [comment]
well it's a typo, thanks for the fix

**Comment by leemorton** [comment]
I can't seem to get past this at the moment, I am logged in to a JupterHub server and after Anomalib install I then downgrade ollama. Then I confirm that as below...
![image](https://github.com/user-attachments/assets/0387287a-829e-4378-8d76-cf5cca4444c9)

However still get the error importing engine... Any thoughts on what I can do?
![image](https://github.com/user-attachments/assets/c5a23b85-3ffd-4a94-b332-7a8885768914)

**Comment by Arman5563** [comment]
I have the same issue as well

**Comment by Arman5563** [comment]
The import problem actually arises for importing the  function, which has been moved/removed in newer ollama versions.
I had the same problem as you, and I tried explicitly importing the function, from ollama._client import _encode_image. But I honestly don't know why my solution worked, as usually explicit imports should not be required.

**Comment by LorenzoF6** [comment]
Ok thank you very much.
So to understand better, i have to explicity import from ollama._client import _encode_image before this code 
from anomalib.data import MVTec
from anomalib.models import Patchcore
from anomalib.engine import Engine 

and then it works fine. it is correct?

**Comment by Arman5563** [comment]
Yes, at least this is what I did and it worked. 
I even used the Vlmad model on my dataset.
I think in ollama>=4.0, the function is actually not there, so ollama<4.0 is actually required.

**Comment by vmiller987** [comment]
Why does your program install the most recent libraries if they are not compatible? So far we have to downgrade three libraries.

- `pip install "numpy<2.0"`
- `pip install "ollama<0.4`
- `pip install "timm==1.0.10"`

**Comment by samet-akcay** [comment]
> Why does your program install the most recent libraries if they are not compatible? So far we have to downgrade three libraries.
> 
> * `pip install "numpy<2.0"`
> * `pip install "ollama<0.4`
> * `pip install "timm==1.0.10"`
> 
> Make it four.
> 
> * 'pip install "matplotlib<3.10"

what do you mean? can you elaborate?

**Comment by vmiller987** [comment]
> > Why does your program install the most recent libraries if they are not compatible? So far we have to downgrade three libraries.
> > 
> > * `pip install "numpy<2.0"`
> > * `pip install "ollama<0.4`
> > * `pip install "timm==1.0.10"`
> > 
> > Make it four.
> > 
> > * 'pip install "matplotlib<3.10"
> 
> what do you mean? can you elaborate?

I was following the documentation on the main page on how to install Anomalib. Am I doing something incorrect? I do remember the first time I installed Anomalib (few months ago?) I believe I had similar issues.
`
python -m venv .venv
source .venv/bin/activate
pip install anomalib[full]
`

Then if I try to do
`anomalib install`

I get the following error
`AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.`

so I have to do 
`pip install "numpy<2.0"`

Then I repeat, and I get the error for this thread which forces me to do
`pip install "ollama<0.4"`

The next one is just a deprecation warning:
`FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers`

It installs at this point. But when I run a PaDiM model,
`engine.train(datamodule=train_data_module, model=model)`

I end up with another error about matplotlib
`AttributeError: 'FigureCanvasAgg' object has no attribute 'tostring_rgb'`

So I have to downgrade `pip install "matplotlib<3.10"`

Then it trains with no issues.

I haven't found any others since.

**Comment by samet-akcay** [comment]
These issues have been addressed in v2. stable release is not on pypi yet, but you could download the beta version. 
https://pypi.org/project/anomalib/2.0.0b2/

Alternatively you could clone the repo and install from source.

**Comment by vmiller987** [comment]
Superb. I thought about making an issue and I'm glad I didn't. That's why I left the comment here.

I'm actually very excited for v2, I just don't have time to test the beta currently and will use the stable release. As soon as I get my current assignment done I will give the v2 beta a test drive. I've been looking forward to the multi-GPU addition.

Thank you for the replies and for the work you've provided. I have learned a lot from Anomalib.

**Comment by LorenzoF6** [comment]
sorry but for me the bug still continue to happen
I install on colab !pip install anomalib[full] the 1.2.0 version (it is located in \usr\local\lib\python 3.11\dist-packages) and the i follow the installation of pip install "ollama<0.4.0" to resolve the bug but if i run from._client import _encode_image colab responds that it can't import _encode_image. 
I checked the class Client in ollama to be sure and _encode_image it is in the correct position, under the Client class.
Any suggestion to manage the bug?

**Comment by vmiller987** [comment]
> sorry but for me the bug still continue to happen I install on colab !pip install anomalib[full] the 1.2.0 version (it is located in \usr\local\lib\python 3.11\dist-packages) and the i follow the installation of pip install "ollama<0.4.0" to resolve the bug but if i run from._client import _encode_image colab responds that it can't import _encode_image. I checked the class Client in ollama to be sure and _encode_image it is in the correct position, under the Client class. Any suggestion to manage the bug?

Did you check the ollama version after you've installed it?
It should be ollama==0.3.3 for Anomalib v1.2.

Take the time and start upgrading your usage code to v2. A lot of improvements have been made for v2 and it's been much nicer using it since I made the switch.

**Comment by LorenzoF6** [comment]
yep ollama's version is 0.3.3, so i don't know how it is possible to happen.

So, i take your suggestion and i think i will install the v2 release

**Comment by djdameln** [comment]
As suggested by others, we would would encourage you to start migrating to v2, since it addresses many of the common issues users were having with v1, and it introduces several ease-of-use additions and an overall smoother workflow. Please be aware that v2 is still in beta release, so it's not 100% stable and there could be some minor API changes before the final release.

Please have a look at readme in the repository root for an overview of the changes in v2, and links to the documentation guides describing the new features.
