### ISSUE TITLE
Gradio Error

### ISSUE THREAD

**Issue by rumanto00** [openvinotoolkit/anomalib#296]
running :
python tools/inference_gradio.py --config ./anomalib/models/patchcore/config.yaml --weight_path ./results/patchcore/mvtec/zipper/weights/model.ckp

error:
Traceback (most recent call last):
  File "tools/inference_gradio.py", line 105, in <module>
    gradio_inferencer = get_inferencer(session_args.config, session_args.weight_path, session_args.meta_data)
  File "tools/inference_gradio.py", line 74, in get_inferencer
    config = get_configurable_parameters(config_path)
  File "/home/rumanto/AI_Development/anomalib/anomalib/config/config.py", line 142, in get_configurable_parameters
    config = OmegaConf.load(config_path)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 183, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rumanto/AI_Development/anomalib/anomalib/models/anomalib/models/patchcore/config.yaml/config.yaml'

any one same result?

**Comment by daMichaelB** [comment]
just a suggestion

the path `/home/rumanto/AI_Development/anomalib/anomalib/models/anomalib/models/patchcore/config.yaml/config.yaml` shows that `config.yaml` is doubled.

maybe try: `--config ./anomalib/models/patchcore/`

**Comment by rumanto00** [comment]
yes. I had try that. it's raise same error (with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory:...)
