### ISSUE TITLE
model training on custom dataset

### ISSUE THREAD

**Issue by niclastrelle** [openvinotoolkit/anomalib#577]
Hi, 

I am trying to train a model, but getting the following error:

```
(venv) niclas@vm-verprobung:~/PycharmProjects/anomalib$ python tools/train.py --config anomalib/models/padim/config.yaml
2022-09-23 10:43:19,631 - pytorch_lightning.utilities.seed - INFO - Global seed set to 42
2022-09-23 10:43:19,632 - anomalib.data - INFO - Loading the datamodule
Traceback (most recent call last):
  File "tools/train.py", line 71, in <module>
    train()
  File "tools/train.py", line 53, in train
    datamodule = get_datamodule(config)
  File "/home/niclas/PycharmProjects/anomalib/venv/lib/python3.8/site-packages/anomalib/data/__init__.py", line 70, in get_datamodule
    mask_dir=config.dataset.mask,
  File "/home/niclas/PycharmProjects/anomalib/venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/home/niclas/PycharmProjects/anomalib/venv/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/niclas/PycharmProjects/anomalib/venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 900, in format_and_raise
    _raise(ex, cause)
  File "/home/niclas/PycharmProjects/anomalib/venv/lib/python3.8/site-packages/omegaconf/_utils.py", line 798, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/niclas/PycharmProjects/anomalib/venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/home/niclas/PycharmProjects/anomalib/venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/niclas/PycharmProjects/anomalib/venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/niclas/PycharmProjects/anomalib/venv/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key mask
    full_key: dataset.mask
    object_type=dict
```

I already tried the fixes in the issue: https://github.com/openvinotoolkit/anomalib/issues/481

Thanks in advance

**Comment by niclastrelle** [comment]
fixed the issue. As it seems the mask parameter in the config.yaml cannot be commented out but has to be leaved empty to be used in a classification task.
