### ISSUE TITLE
urllib.error.URLError: <urlopen error [WinError 10061]，Loading pretrained weights from url Downloading

### ISSUE THREAD

**Issue by monkeycc** [openvinotoolkit/anomalib#678]
`python tools/train.py --model cflow`

```
2022-11-04 14:52:33,362 - anomalib.data - INFO - Loading the datamodule
2022-11-04 14:52:33,363 - anomalib.pre_processing.pre_process - WARNING - Transform configs has not been provided. Images will be normalized using ImageNet statistics.
2022-11-04 14:52:33,364 - anomalib.pre_processing.pre_process - WARNING - Transform configs has not been provided. Images will be normalized using ImageNet statistics.
2022-11-04 14:52:33,364 - anomalib.models - INFO - Loading the model.
2022-11-04 14:52:33,365 - anomalib.models.components.base.anomaly_module - INFO - Initializing CflowLightning model.
D:\anaconda3ok\envs\anomalib_env\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
2022-11-04 14:52:34,202 - timm.models.helpers - INFO - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/wide_resnet50_racm-8234f177.pth)
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/wide_resnet50_racm-8234f177.pth" to C:\Users\AI/.cache\torch\hub\checkpoints\wide_resnet50_racm-8234f177.pth
Traceback (most recent call last):
  File "D:\anaconda3ok\envs\anomalib_env\lib\urllib\request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\anaconda3ok\envs\anomalib_env\lib\http\client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\anaconda3ok\envs\anomalib_env\lib\http\client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\anaconda3ok\envs\anomalib_env\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\anaconda3ok\envs\anomalib_env\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "D:\anaconda3ok\envs\anomalib_env\lib\http\client.py", line 951, in send
    self.connect()
  File "D:\anaconda3ok\envs\anomalib_env\lib\http\client.py", line 1418, in connect
    super().connect()
  File "D:\anaconda3ok\envs\anomalib_env\lib\http\client.py", line 922, in connect
    self.sock = self._create_connection(
  File "D:\anaconda3ok\envs\anomalib_env\lib\socket.py", line 808, in create_connection
    raise err
  File "D:\anaconda3ok\envs\anomalib_env\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 71, in <module>
    train()
  File "tools/train.py", line 54, in train
    model = get_model(config)
  File "D:\anaconda3ok\envs\anomalib_env\lib\site-packages\anomalib\models\__init__.py", line 90, in get_model
    model = getattr(module, f"{_snake_to_pascal_case(config.model.name)}Lightning")(config)
  File "D:\anaconda3ok\envs\anomalib_env\lib\site-packages\anomalib\models\cflow\lightning_model.py", line 184, in __init__
    super().__init__(
  File "D:\anaconda3ok\envs\anomalib_env\lib\site-packages\anomalib\models\cflow\lightning_model.py", line 46, in __init__
    self.model: CflowModel = CflowModel(
  File "D:\anaconda3ok\envs\anomalib_env\lib\site-packages\anomalib\models\cflow\torch_model.py", line 41, in __init__
    self.encoder = FeatureExtractor(backbone=self.backbone, layers=self.pool_layers, pre_trained=pre_trained)
  File "D:\anaconda3ok\envs\anomalib_env\lib\site-packages\anomalib\models\components\feature_extractors\feature_extractor.py", line 43, in __init__
    self.feature_extractor = timm.create_model(
  File "D:\anaconda3ok\envs\anomalib_env\lib\site-packages\timm\models\factory.py", line 74, in create_model
    model = create_fn(pretrained=pretrained, **kwargs)
  File "D:\anaconda3ok\envs\anomalib_env\lib\site-packages\timm\models\resnet.py", line 876, in wide_resnet50_2
    return _create_resnet('wide_resnet50_2', pretrained, **model_args)
  File "D:\anaconda3ok\envs\anomalib_env\lib\site-packages\timm\models\resnet.py", line 694, in _create_resnet
    return build_model_with_cfg(
  File "D:\anaconda3ok\envs\anomalib_env\lib\site-packages\timm\models\helpers.py", line 465, in build_model_with_cfg
    load_pretrained(
  File "D:\anaconda3ok\envs\anomalib_env\lib\site-packages\timm\models\helpers.py", line 189, in load_pretrained
    state_dict = load_state_dict_from_url(pretrained_url, progress=progress, map_location='cpu')
  File "D:\anaconda3ok\envs\anomalib_env\lib\site-packages\torch\hub.py", line 727, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "D:\anaconda3ok\envs\anomalib_env\lib\site-packages\torch\hub.py", line 593, in download_url_to_file
    u = urlopen(req)
  File "D:\anaconda3ok\envs\anomalib_env\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\anaconda3ok\envs\anomalib_env\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\anaconda3ok\envs\anomalib_env\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\anaconda3ok\envs\anomalib_env\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "D:\anaconda3ok\envs\anomalib_env\lib\urllib\request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\anaconda3ok\envs\anomalib_env\lib\urllib\request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
```

You can't visit github in China

Can. pth customize files ?

**Comment by samet-akcay** [comment]
@monkeycc, not sure if I understand the question. Looks like you cannot download the timm weights. Can you somehow manually download the weights?

**Comment by samet-akcay** [comment]
I'm converting this to a discussion and discuss it there.
