### ISSUE TITLE
Change precision from 32 to 16

### ISSUE THREAD

**Issue by rumanto00** [openvinotoolkit/anomalib#718]
On the config file, there is a precision entry said 32. is this mean FP32? 
When I change to 16 (mean FP16) it generates an error as follows:

How to change precision on training & Inference?

Thanks

2022-11-18 15:04:01,672 - anomalib.data - INFO - Loading the datamodule
2022-11-18 15:04:01,673 - anomalib.pre_processing.pre_process - WARNING - Transform configs has not been provided. Images will be normalized using ImageNet statistics.
2022-11-18 15:04:01,673 - anomalib.pre_processing.pre_process - WARNING - Transform configs has not been provided. Images will be normalized using ImageNet statistics.
2022-11-18 15:04:01,673 - anomalib.models - INFO - Loading the model.
2022-11-18 15:04:01,678 - torch.distributed.nn.jit.instantiator - INFO - Created a temporary directory at /tmp/tmp39b316j9
2022-11-18 15:04:01,679 - torch.distributed.nn.jit.instantiator - INFO - Writing /tmp/tmp39b316j9/_remote_module_non_sriptable.py
/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/torch/distributed/_sharded_tensor/__init__.py:8: DeprecationWarning: torch.distributed._sharded_tensor will be deprecated, use torch.distributed._shard.sharded_tensor instead
  warnings.warn(
2022-11-18 15:04:01,685 - anomalib.models.components.base.anomaly_module - INFO - Initializing PatchcoreLightning model.
/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
2022-11-18 15:04:02,730 - timm.models.helpers - INFO - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/wide_resnet50_racm-8234f177.pth)
2022-11-18 15:04:02,959 - anomalib.utils.loggers - INFO - Loading the experiment logger(s)
2022-11-18 15:04:02,959 - anomalib.utils.callbacks - INFO - Loading the callbacks
2022-11-18 15:04:02,961 - anomalib.utils.callbacks - INFO - Setting model export to onnx
2022-11-18 15:04:02,962 - pytorch_lightning.utilities.rank_zero - INFO - Using 16bit native Automatic Mixed Precision (AMP)
2022-11-18 15:04:02,963 - pytorch_lightning.utilities.rank_zero - INFO - GPU available: True, used: True
2022-11-18 15:04:02,963 - pytorch_lightning.utilities.rank_zero - INFO - TPU available: False, using: 0 TPU cores
2022-11-18 15:04:02,963 - pytorch_lightning.utilities.rank_zero - INFO - IPU available: False, using: 0 IPUs
2022-11-18 15:04:02,963 - pytorch_lightning.utilities.rank_zero - INFO - HPU available: False, using: 0 HPUs
2022-11-18 15:04:02,963 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
2022-11-18 15:04:02,963 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
2022-11-18 15:04:02,963 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_test_batches=1.0)` was configured so 100% of the batches will be used..
2022-11-18 15:04:02,963 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(limit_predict_batches=1.0)` was configured so 100% of the batches will be used..
2022-11-18 15:04:02,963 - pytorch_lightning.utilities.rank_zero - INFO - `Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
2022-11-18 15:04:02,963 - anomalib - INFO - Training the model.
2022-11-18 15:04:02,967 - anomalib.data.mvtec - INFO - Found the dataset.
2022-11-18 15:04:02,967 - anomalib.data.mvtec - INFO - Setting up train, validation, test and prediction datasets.
/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `ROC` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
2022-11-18 15:04:05,328 - pytorch_lightning.accelerators.gpu - INFO - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py:183: UserWarning: `LightningModule.configure_optimizers` returned `None`, this fit will run with no optimizer
  rank_zero_warn(
2022-11-18 15:04:05,331 - pytorch_lightning.callbacks.model_summary - INFO - 
  | Name                  | Type                     | Params
-------------------------------------------------------------------
0 | image_threshold       | AnomalyScoreThreshold    | 0     
1 | pixel_threshold       | AnomalyScoreThreshold    | 0     
2 | model                 | PatchcoreModel           | 24.9 M
3 | image_metrics         | AnomalibMetricCollection | 0     
4 | pixel_metrics         | AnomalibMetricCollection | 0     
5 | normalization_metrics | MinMax                   | 0     
-------------------------------------------------------------------
24.9 M    Trainable params
0         Non-trainable params
24.9 M    Total params
49.725    Total estimated model params size (MB)
Epoch 0:   0%|                                                                                                                                 | 0/10 [00:00<?, ?it/s]/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py:137: UserWarning: `training_step` returned `None`. If this was on purpose, ignore this warning...
  self.warning_cache.warn("`training_step` returned `None`. If this was on purpose, ignore this warning...")
Traceback (most recent call last):
  File "tools/train.py", line 71, in <module>
    train()
  File "tools/train.py", line 60, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 208, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 203, in advance
    result = self._run_optimization(
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 256, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 369, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1595, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1646, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 193, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/native_amp.py", line 87, in optimizer_step
    self.scaler.unscale_(optimizer)
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 265, in unscale_
    self._check_scale_growth_tracker("unscale_")
  File "/home/rumanto/miniconda3/envs/anomalib_env/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 137, in _check_scale_growth_tracker
    assert self._scale is not None, "Attempted {} but _scale is None.  ".format(funcname) + fix
**AssertionError: Attempted unscale_ but _scale is None.  This may indicate your script did not use scaler.scale(loss or outputs) earlier in the iteration.**
Epoch 0:   0%|          | 0/10 [00:02<?, ?it/s]

**Comment by djdameln** [comment]
Hi, the `precision` argument in the Anomalib config is inherited from the Pytorch Lightning trainer arguments (see PL's [documentation](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.Trainer.html) on this topic). Based on a quick search on the PL forums, it seems that changing the precision argument leads to an error when no loss function is defined (https://forums.pytorchlightning.ai/t/error-with-mixed-precision-16bit/528). Since PatchCore training does not involve optimization and hence does not use a loss function, it seems that this model is not compatible with PL's reduced-precision training.

**Comment by rumanto00** [comment]
Hi djdamein,

Thank you for your explanation.
So if we want to reduce precision should be done after training? 
is this count as a bug or a future request?

Regards,
Yuliadi

**Comment by djdameln** [comment]
I can't think of a theoretical motivation why mixed precision would not be available for models that do not report loss, like PatchCore. So I don't see any reason why PL would not support this. I therefore feel that this issue is more on the Pytorch Lightning side than on the Anomalib side. 

If you're using Anomalib's [PL inferencer](https://github.com/openvinotoolkit/anomalib/blob/main/tools/inference/lightning_inference.py), you can run inference with mixed precision by setting the `precision` parameter to 16 in the config file that you pass to the inference script. I can confirm that PatchCore inference runs fine with this setting enabled. I'm not sure exactly about the implications of mixed precision inference after full precision training, but from the top of my head I don't see any issues there. In the quick tests that I ran the results look fine.

If your goal is to speed up inference and you're running your models on intel hardware, I would suggest you to also have a look at the OpenVINO [export](https://openvinotoolkit.github.io/anomalib/tutorials/export.html#export) and [inference](https://openvinotoolkit.github.io/anomalib/tutorials/inference.html#openvino-inference) capabilities of Anomalib. The OpenVINO model optimizer supports FP16 compression, among other optimization techniques. Please note that the default Model Optimizer configuration used by Anomalib's export callback does not involve FP16 compression (configuring the MO settings is a [WIP](https://github.com/openvinotoolkit/anomalib/issues/739)). So, if you want to export your models to OpenVINO with non-default settings, you will be required to run the Model Optimizer separately on the exported ONNX model. If you don't have any experience with OpenVINO's Model Optimizer, [this guide](https://docs.openvino.ai/latest/openvino_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html) should help you get started.

**Comment by rumanto00** [comment]
Hi djdamein,

Thank You again for your detail and clear explanations. I will try to do MO after training as you mention for intel hardware.

For intel hardware, is new Intel ARC are support by Openvino while doing inference?

Thanks,
Yuliadi.

**Comment by djdameln** [comment]
Intel® Arc GPU is listed on this page as a supported device, so in theory you should be able to run OpenVINO models on Arc GPUs. However, we have not tested this for any of the Anomalib models.

Please note that Anomalib's OpenVINO inferencer runs on CPU by default. This can be changed by passing the `--device` parameter when running the entrypoint script. To run on Intel® Arc GPU, you will have to set this parameter to "GPU". This option has been added very recently, so you might need to update your Anomalib installation.

**Comment by djdameln** [comment]
@rumanto00 I'm closing this issue for now. Feel free to re-open or start a [new discussion thread](https://github.com/openvinotoolkit/anomalib/discussions/new) if you have any follow-up questions.

**Comment by glucasol** [comment]
Hi, @rumanto00 !

Were you able to optimize the model using FP16 compression in OpenVINO MO?
If yes, how did you do that?

Regards.
