### ISSUE TITLE
Dataset extraction error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [openvinotoolkit/anomalib#835]
When I tried to run using the following command line, 

```
python3 tools/train.py --config anomalib/models/padim/config.yaml
```

the following error saying "Unrecognized file format: datasets/MVTec/420938113-1629952094" occurrd.

```
023-01-12 17:20:27,177 - anomalib - INFO - Training the model.
2023-01-12 17:20:27,181 - anomalib.data.utils.download - INFO - Downloading the mvtec dataset.
mvtec: 5.26GB [16:26, 5.34MB/s]                                                                                           
2023-01-12 17:36:53,638 - anomalib.data.utils.download - INFO - Checking the hash of the downloaded file.
2023-01-12 17:37:02,944 - anomalib.data.utils.download - INFO - Extracting dataset into root folder.
Traceback (most recent call last):
  File "tools/train.py", line 75, in <module>
    train()
  File "tools/train.py", line 61, in train
    trainer.fit(model=model, datamodule=datamodule)
  File "/home/dl/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/dl/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/dl/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/dl/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1164, in _run
    self._data_connector.prepare_data()
  File "/home/dl/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 124, in prepare_data
    self.trainer.datamodule.prepare_data()
  File "/home/dl/anomalib/anomalib/data/mvtec.py", line 260, in prepare_data
    download_and_extract(self.root, DOWNLOAD_INFO)
  File "/home/dl/anomalib/anomalib/data/utils/download.py", line 248, in download_and_extract
    raise ValueError(f"Unrecognized file format: {downloaded_file_path}")
ValueError: Unrecognized file format: datasets/MVTec/420938113-1629952094
```

Please let me know how to fix it !

**Comment by samet-akcay** [comment]
Hi @Ishihara-Masabumi, looks like this happens when the code tries to download the MVTec dataset. Do you have the MVTec dataset on your file system? If yes, can you try to train the model using the same CLI command? If it works, we would know that the script only fails when trying to download the dataset.

**Comment by samet-akcay** [comment]
Also reported in #838. @djdameln, can you have a look at this to check if this is a bug?

**Comment by Ishihara-Masabumi** [comment]
It's OK.
Thanks.
