### ISSUE TITLE
lightning_inference.py error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [openvinotoolkit/anomalib#852]
When I ran lightning_inference.py as instructed in https://github.com/openvinotoolkit/anomalib#inference, the following error occurred.

```
$ python tools/inference/lightning_inference.py \
>     --config anomalib/models/padim/config.yaml \
>     --weights results/padim/mvtec/bottle/weights/model.ckpt \
>     --input datasets/MVTec/bottle/test/broken_large/000.png \
>     --output results/padim/mvtec/bottle/images
/home/ishihara/anomalib/anomalib/config/config.py:274: UserWarning: config.project.unique_dir is set to False. This does not ensure that your results will be written in an empty directory and you may overwrite files.
  warn(
/home/ishihara/.local/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: DeprecationWarning: From v0.10 an `'Binary*'`, `'Multiclass*', `'Multilabel*'` version now exist of each classification metric. Moving forward we recommend using these versions. This base metric will still work as it did prior to v0.10 until v0.11. From v0.11 the `task` argument introduced in this metric will be required and the general order of arguments may change, such that this metric will just function as an single entrypoint to calling the three specialized versions.
  warnings.warn(*args, **kwargs)
/home/ishihara/.local/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
FeatureExtractor is deprecated. Use TimmFeatureExtractor instead. Both FeatureExtractor and TimmFeatureExtractor will be removed in version 2023.1
/home/ishihara/anomalib/anomalib/utils/callbacks/__init__.py:141: UserWarning: Export option: None not found. Defaulting to no model export
  warnings.warn(f"Export option: {config.optimization.export_mode} not found. Defaulting to no model export")
/home/ishihara/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py:51: LightningDeprecationWarning: Setting `Trainer(resume_from_checkpoint=)` is deprecated in v1.5 and will be removed in v1.7. Please pass `Trainer.fit(ckpt_path=)` directly instead.
  rank_zero_deprecation(
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
`Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
`Trainer(limit_test_batches=1.0)` was configured so 100% of the batches will be used..
`Trainer(limit_predict_batches=1.0)` was configured so 100% of the batches will be used..
`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
Traceback (most recent call last):
  File "tools/inference/lightning_inference.py", line 87, in <module>
    infer()
  File "tools/inference/lightning_inference.py", line 79, in infer
    dataset = InferenceDataset(args.input, image_size=tuple(config.dataset.image_size), transform=transform)
  File "/home/ishihara/anomalib/anomalib/data/inference.py", line 34, in __init__
    self.image_filenames = get_image_filenames(path)
  File "/home/ishihara/anomalib/anomalib/data/utils/image.py", line 39, in get_image_filenames
    if len(image_filenames) == 0:
UnboundLocalError: local variable 'image_filenames' referenced before assignment
```

**Comment by samet-akcay** [comment]
Do you have the dataset in this location?
`datasets/MVTec/bottle/test/broken_large/000.png`

**Comment by Ishihara-Masabumi** [comment]
Woops! There is another error below.

```
$ python tools/inference/lightning_inference.py \
>     --config anomalib/models/padim/config.yaml \
>     --weights results/padim/mvtec/bottle/weights/model.ckpt \
>     --input datasets/MVTec/bottle/test/broken_large/000.png \
>     --output results/padim/mvtec/bottle/images
  File "tools/inference/lightning_inference.py", line 19
    def get_args() -> Namespace:
                   ^
SyntaxError: invalid syntax
```
