### ISSUE TITLE
openvino_inference.py error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [openvinotoolkit/anomalib#853]
When I ran openvino_inference.py as instructed in https://github.com/openvinotoolkit/anomalib, the following error occurred.

```
$ python tools/inference/openvino_inference.py \
>     --config anomalib/models/padim/config.yaml \
>     --weights results/padim/mvtec/bottle/openvino/openvino_model.bin \
>     --meta_data results/padim/mvtec/bottle/openvino/meta_data.json \
>     --input datasets/MVTec/bottle/test/broken_large/000.png \
>     --output results/padim/mvtec/bottle/images
/home/ishihara/anomalib/anomalib/config/config.py:274: UserWarning: config.project.unique_dir is set to False. This does not ensure that your results will be written in an empty directory and you may overwrite files.
  warn(
Traceback (most recent call last):
  File "tools/inference/openvino_inference.py", line 108, in <module>
    infer()
  File "tools/inference/openvino_inference.py", line 82, in infer
    inferencer = OpenVINOInferencer(
  File "/home/ishihara/anomalib/anomalib/deploy/inferencers/openvino_inferencer.py", line 52, in __init__
    self.input_blob, self.output_blob, self.network = self.load_model(path)
  File "/home/ishihara/anomalib/anomalib/deploy/inferencers/openvino_inferencer.py", line 78, in load_model
    network = ie_core.read_network(xml_path, bin_path)
  File "ie_api.pyx", line 367, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 401, in openvino.inference_engine.ie_api.IECore.read_network
Exception: Path to the model results/padim/mvtec/bottle/openvino/openvino_model.xml doesn't exist or it's a directory
```

**Comment by samet-akcay** [comment]
Can you share your config file. Similar to #854, you may not have trained the model yet, which should generate the openvino model. (Note that to generate the openvino model, you need to configure the config file as instructed on the [README.md](https://github.com/openvinotoolkit/anomalib#exporting-model-to-onnx-or-openvino-ir) file.

**Comment by Ishihara-Masabumi** [comment]
About the next your commnet, no I don't generate the openvino model. 
Because I'd like to use pretrained model.

**Comment by samet-akcay** [comment]
> I understood that python means v2.7 and python3 means v3.8 on my PC. Thanks.

To avoid such issues, I highly recommend you use [virtual environments](https://github.com/openvinotoolkit/anomalib#local-install). 

Regarding your config file, you need to change the following section 
```yaml
optimization:
  export_mode: null #options: onnx, openvino
```

to 

```yaml
optimization:
  export_mode: openvino #options: onnx, openvino
```

If `export_mode` is not openvino, anomalib cannot create an openvino model.

**Comment by samet-akcay** [comment]
Since this is not an issue, I'm moving this to Q&A in discussions. Feel free to ask more questions from there.
