### ISSUE TITLE
gradio_inference.py error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [openvinotoolkit/anomalib#854]
When I ran gradio_inference.py as instructed on https://github.com/openvinotoolkit/anomalib, the following error occurred.

```
$ python tools/inference/gradio_inference.py \
>         --config ./anomalib/models/padim/config.yaml \
>         --weights ./results/padim/mvtec/bottle/weights/model.ckpt
/home/ishihara/anomalib/anomalib/config/config.py:274: UserWarning: config.project.unique_dir is set to False. This does not ensure that your results will be written in an empty directory and you may overwrite files.
  warn(
/home/ishihara/.local/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: DeprecationWarning: From v0.10 an `'Binary*'`, `'Multiclass*', `'Multilabel*'` version now exist of each classification metric. Moving forward we recommend using these versions. This base metric will still work as it did prior to v0.10 until v0.11. From v0.11 the `task` argument introduced in this metric will be required and the general order of arguments may change, such that this metric will just function as an single entrypoint to calling the three specialized versions.
  warnings.warn(*args, **kwargs)
/home/ishihara/.local/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
FeatureExtractor is deprecated. Use TimmFeatureExtractor instead. Both FeatureExtractor and TimmFeatureExtractor will be removed in version 2023.1
Traceback (most recent call last):
  File "tools/inference/gradio_inference.py", line 99, in <module>
    gradio_inferencer = get_inferencer(args.config, args.weights, args.meta_data)
  File "tools/inference/gradio_inference.py", line 66, in get_inferencer
    inferencer = torch_inferencer(config=config_path, model_source=weight_path, meta_data_path=meta_data_path)
  File "/home/ishihara/anomalib/anomalib/deploy/inferencers/torch_inferencer.py", line 60, in __init__
    self.model = self.load_model(model_source)
  File "/home/ishihara/anomalib/anomalib/deploy/inferencers/torch_inferencer.py", line 110, in load_model
    model.load_state_dict(torch.load(path, map_location=self.device)["state_dict"])
  File "/home/ishihara/.local/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ishihara/.local/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ishihara/.local/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'results/padim/mvtec/bottle/weights/model.ckpt'
```

**Comment by samet-akcay** [comment]
Looks like you haven't trained a model yet. Can you check if you trained the model?

**Comment by Ishihara-Masabumi** [comment]
No, I haven't trained a model, yet.
I'd like to use pretrained model, so please let me know how to get the pretrained model.

**Comment by samet-akcay** [comment]
Alright, I'm closing this one then.
