### ISSUE TITLE
[Bug]: self.kernel = self.kernel.expand(channels, -1, -1, -1)

### ISSUE THREAD

**Issue by majintao1994** [openvinotoolkit/anomalib#920]
### Describe the bug

After I installed the environment according to the document and downloaded the dataset you provided, the training program failed to run, and the following error was reported
RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]): the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)。
What is the problem？

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

train

### OS information

OS information:
Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: GeForce RTX 2070
CUDA_HOME: /usr/local/cuda-10.0
NVCC: Cuda compilation tools, release 10.0, V10.0.13
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.13.0

### Expected behavior

train

### Pip/GitHub

GitHub

### What version/branch did you use?

master

### Configuration YAML

```yaml
Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@majintao1994 
openvinotoolkit
/
anomalib
Public
Fork your own copy of openvinotoolkit/anomalib
Code
Issues
22
Pull requests
8
Discussions
Actions
Projects
Security
Insights
anomalib/anomalib/models/padim/config.yaml
@samet-akcay
samet-akcay Bump PyTorch Lightning version to v1.9.* (#870)
…
Latest commit d390fb5 2 weeks ago
 History
 9 contributors
@samet-akcay@ashwinvaidya17@djdameln@sherpan@Lothiraldan@ashishbdatta@AlexanderDokuchaev@alexriedel1@jpcbertoldo
109 lines (102 sloc)  2.97 KB

dataset:
  name: mvtec
  format: mvtec
  path: ./datasets/MVTec
  category: bottle
  task: segmentation
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: padim
  backbone: resnet18
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null #options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
anomalib/config.yaml at main · openvinotoolkit/anomalib
```

### Logs

```shell
Global seed set to 42
2023-02-20 08:19:25,694 - anomalib.data - INFO - Loading the datamodule
2023-02-20 08:19:25,694 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2023-02-20 08:19:25,694 - anomalib.data.utils.transform - INFO - No config file has been provided. Using default transforms.
2023-02-20 08:19:25,694 - anomalib.models - INFO - Loading the model.
2023-02-20 08:19:25,695 - anomalib.models.components.base.anomaly_module - INFO - Initializing PadimLightning model.
/home/ty/anaconda3/envs/anomalib_env/lib/python3.8/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to  large memory footprint.
  warnings.warn(*args, **kwargs)
2023-02-20 08:19:25,699 - anomalib.models.components.feature_extractors.timm - FeatureExtractor is deprecated. Use TimmFeatureExtractor instead. Both FeatureExtractor and TimmFeatureExtractor will be removed in a future release.
2023-02-20 08:19:25,907 - timm.models.helpers - INFO - Loading pretrained weights from url (https://download.pytorch.org/models/resnet18-5c106cde.pth)
Traceback (most recent call last):
File "/home/work/anomalib-main/tools/train.py", line 75, in <module>
    train()
File "/home/work/anomalib-main/tools/train.py", line 55, in train
model = get_model(config)
File "/home/work/anomalib-main/anomalib/models/__init__.py", line 100, in get_model
model = getattr(module, f"{_snake_to_pascal_case(config.model.name)}Lightning")(config)
File "/home/work/anomalib-main/anomalib/models/padim/lightning_model.py", line 123,in __init__
    super().__init__(
File "/home/work/anomalib-main/anomalib/models/padim/lightning_model.py",line 49, in __init__
    self.model: PadimModel = PadimModel(
 File "/home/work/anomalib-main/anomalib/models/padim/torch_model.py", line 99, in __init__
    self.anomaly_map_generator = AnomalyMapGenerator(image_size=input_size)
File "/home/work/anomalib-main/anomalib/models/padim/anomaly_map.py",  line 28, in __init__
    self.blur = GaussianBlur2d(kernel_size=(kernel_size, kernel_size), sigma=(sigma, sigma), channels=1)
 File "/home/work/anomalib-main/anomalib/models/components/filters/blur.py", line 67, in __init__
    self.kernel = self.kernel.expand(channels, -1, -1, -1)
RuntimeError: expand(torch.FloatTensor{[1, 1, 1, 33, 33]}, size=[1, -1, -1, -1]):the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samet-akcay** [comment]
@majintao1994, looks like kornia released a new [version](https://pypi.org/project/kornia/0.6.10/) on Friday. You could downgrade the kornia version for now. We'll work on a fix later. Cheers!

**Comment by ashwinvaidya17** [comment]
I am closing this as the requirements now limit the version of Kornia.

**Comment by LiAnGGGGGG** [comment]
I had the same problem and reduced kornia==0.6.12 to kornia==0.6.9 to work properly
